[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/track"
  to = "/.netlify/functions/track"
  status = 200
  force = true

[[redirects]]
  from = "/api/stats"
  to = "/.netlify/functions/stats"
  status = 200
  force = true
